config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", views.home, name="home"),
    path('users/files/', include('files.urls')),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("users/notes/", include("notes.urls")),
    path("users/contacts/", include("contacts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

files/urls.py
from django.urls import path
from .views import file_list, download_file, delete_file, upload_file

urlpatterns = [
    path('upload/', upload_file, name='image_upload'),
    path('', file_list, name='file_list'),
    path('download/<int:file_id>/', download_file, name='download_file'),
    path('delete/<int:file_id>/', delete_file, name='delete_file'),
]

personal_assistant/personal_assistant/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path('users/', include('users.urls')),
    path('', views.home, name='home'),]

users/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views

from .forms import LoginForm

app_name = "users"

urlpatterns = [
    path("registration/", views.RegisterView.as_view(), name="registration"),
    path(
        "login/",
        views.CustomLoginView.as_view(
            template_name="users/login.html",
            form_class=LoginForm,
            redirect_authenticated_user=True,
            success_url=reverse_lazy("users:profile", kwargs={"username": "username"}),
        ),
        name="login",
    ),
    path("logout/", LogoutView.as_view(next_page="home"), name="logout"),
    path("accounts/profile/<str:username>/", views.profile, name="profile"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

users/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models
from django.utils import timezone
from PIL import Image


class CustomUser(AbstractUser):
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.username

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import (
    CharField,
    TextInput,
    EmailInput,
    EmailField,
    PasswordInput,

)


class RegisterForm(UserCreationForm):
    username = CharField(
        max_length=16,
        min_length=3,
        required=True,
        widget=TextInput(attrs={"class": "form-control"}),
    )
    email = EmailField(
        max_length=50, required=True, widget=EmailInput(attrs={"class": "form-control"})
    )
    password1 = CharField(
        required=True, widget=PasswordInput(attrs={"class": "form-control"})
    )
    password2 = CharField(
        required=True, widget=PasswordInput(attrs={"class": "form-control"})
    )

    class Meta:
        model = get_user_model()
        fields = ("username", "email", "password1", "password2")


class LoginForm(AuthenticationForm):
    username = CharField(
        max_length=16,
        min_length=3,
        required=True,
        widget=TextInput(attrs={"class": "form-control"}),
    )
    password = CharField(
        required=True, widget=PasswordInput(attrs={"class": "form-control"})
    )

    class Meta:
        model = get_user_model()
        fields = ("username", "password")

users/views.py
import json

from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView, LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.management import call_command
from django.core.cache import cache
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views import View
from django.contrib import messages
from django.shortcuts import render

from .forms import RegisterForm
from .models import CustomUser


class RegisterView(View):
    template_name = "users/registration.html"
    form_class = RegisterForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="users:login")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f"Account created successfully")
            return redirect(to="users:login")
        return render(request, self.template_name, {"form": form})


class CustomLoginView(LoginView):
    def get_success_url(self):
        username = self.request.user.username
        return reverse("users:profile", kwargs={"username": username})

    def form_invalid(self, form):
        messages.error(self.request, "Wrong username or password")
        return super().form_invalid(form)


@login_required
def profile(request, username):
    last_scrape_time = cache.get("last_scrape_time")
    now = timezone.now()
    if not last_scrape_time or (now - last_scrape_time).total_seconds() > 3600:
        call_command("scrape_news")
        cache.set("last_scrape_time", now, timeout=None)

    try:
        with open("utils/categorized_news.json", "r", encoding="utf-8") as file:
            categorized_news = json.load(file)
    except FileNotFoundError:
        categorized_news = {}

    user = get_object_or_404(CustomUser, username=username)
    return render(
        request,
        "users/profile.html",
        {
            "user": user,
            "categorized_news": categorized_news,
        },
    )


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = "users/password_reset.html"
    email_template_name = "users/password_reset_email.html"
    html_email_template_name = "users/password_reset_email.html"
    success_url = reverse_lazy("users:password_reset_done")
    success_message = (
        "An email with instructions to reset your password has been sent to %(email)s."
    )
    subject_template_name = "users/password_reset_subject.txt"

users/templates/users/login.html
{% extends "users/base.html" %}

{% block content %}
<div>
    <h2>Login</h2>
</div>

<form method="post" style="color: #2EA1D9;" action="{% url 'users:login' %}">
    {% csrf_token %}
    <div >
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <div>
        <label> Password:
            {{ form.password }}
        </label>
        <span>{{ form.errors.password }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
    <div class="small" style="text-align: left;">
        <a href="{% url "users:password_reset" %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
</form>
{% endblock %}

users/templates/users/logout.html
{% extends "users/base.html" %}

{% block content %}
    <div class="container mt-3">
        <h1>Hope to see you again</h1>
    </div>
{% endblock %}

users/templates/users/password_reset.html
{% extends "users/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post" style="color: #2EA1D9;">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "users/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "users/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post" style="color: #2EA1D9;">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends "users/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

users/templates/users/profile.html
{% extends "users/base.html" %}

{% block content %}

<div class="profile-container">
    <!-- Ліва колонка -->
    <div class="left-column">
        <div>
            <h1 class = "profile" >profile: {{user.username}}</h1>

        </div>

        {% if messages %}
        <div>
            {% for message in messages %}
            <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
            {% endfor %}
        </div>
        {% endif %}


        <div class="grid" style="margin-top: 20px;">
            <a href="{% url 'contact_list'%}" class="btn btn-modern">My Contacts</a>
            <a href="{% url 'main_url' %}" class="btn btn-modern">My Notes</a>
            <a href="{% url 'file_list' %}" class="btn btn-modern">My Files</a>
        </div>
    </div>
    <!-- Права колонка для новин -->
    <div class="right-column">
        <h2 class="news-title">Latest News</h2>
        <div class="news-sections">
            {% for category, news_items in categorized_news.items %}
            <div class="news-category">
                <h3>{{ category|capfirst }}</h3>
                <div class="news-list-wrapper">
                    <ul class="news-list">
                        {% for news_item in news_items %}
                        <li>
                            <a href="{{ news_item.link }}">{{ news_item.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

</div>

{% endblock content %}

users/templates/users/registration.html
{% extends "users/base.html" %}

{% block content %}

<div class="mb-3">
    <h2>Registration</h2>
     {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}
</div>

<form method="post" style="color: #2EA1D9;" action="{% url 'users:registration' %} ">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label"> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <div>
        <label class="form-label"> Email:
            {{ form.email }}
        </label>
        <span>{{ form.errors.email }}</span>
    </div>
    <br>
    <div class="mb-3">
        <label class="form-label"> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div class="mb-3">
        <label class="form-label"> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}